openapi: 3.0.3
info:
  title: Utibu Health Pharmacy API
  version: 1.0.0
  description: API for interacting with Utibu Health Pharmacy database to serve customers
    through a mobile application.
paths:
  /pharmacy/api/:
    get:
      operationId: pharmacy_api_retrieve
      tags:
      - pharmacy
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /pharmacy/api/customers/:
    get:
      operationId: pharmacy_api_customers_list
      tags:
      - pharmacy
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'
          description: ''
    post:
      operationId: pharmacy_api_customers_create
      tags:
      - pharmacy
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Customer'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Customer'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
          description: ''
  /pharmacy/api/customers/{id}/:
    get:
      operationId: pharmacy_api_customers_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - pharmacy
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
          description: ''
    put:
      operationId: pharmacy_api_customers_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - pharmacy
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Customer'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Customer'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
          description: ''
    patch:
      operationId: pharmacy_api_customers_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - pharmacy
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedCustomer'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedCustomer'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedCustomer'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
          description: ''
    delete:
      operationId: pharmacy_api_customers_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - pharmacy
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /pharmacy/api/medications/:
    get:
      operationId: pharmacy_api_medications_list
      tags:
      - pharmacy
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MedicationGET'
          description: ''
    post:
      operationId: pharmacy_api_medications_create
      tags:
      - pharmacy
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MedicationPOST'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/MedicationPOST'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/MedicationPOST'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MedicationPOST'
          description: ''
  /pharmacy/api/medications/{id}/:
    get:
      operationId: pharmacy_api_medications_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - pharmacy
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MedicationGET'
          description: ''
    put:
      operationId: pharmacy_api_medications_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - pharmacy
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MedicationPOST'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/MedicationPOST'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/MedicationPOST'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MedicationPOST'
          description: ''
    patch:
      operationId: pharmacy_api_medications_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - pharmacy
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedMedicationPOST'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedMedicationPOST'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedMedicationPOST'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MedicationPOST'
          description: ''
    delete:
      operationId: pharmacy_api_medications_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - pharmacy
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /pharmacy/api/orders/:
    get:
      operationId: pharmacy_api_orders_list
      tags:
      - pharmacy
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
          description: ''
    post:
      operationId: pharmacy_api_orders_create
      tags:
      - pharmacy
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Order'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Order'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
          description: ''
  /pharmacy/api/orders/{id}/:
    get:
      operationId: pharmacy_api_orders_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - pharmacy
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
          description: ''
    put:
      operationId: pharmacy_api_orders_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - pharmacy
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Order'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Order'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
          description: ''
    patch:
      operationId: pharmacy_api_orders_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - pharmacy
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedOrder'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedOrder'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedOrder'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
          description: ''
    delete:
      operationId: pharmacy_api_orders_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - pharmacy
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
components:
  schemas:
    Customer:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        address:
          type: string
        phone_number:
          type: string
          maxLength: 15
        user:
          type: integer
      required:
      - address
      - id
      - phone_number
      - user
    MedicationGET:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 100
        medication_image:
          type: string
          format: uri
        description:
          type: string
        short_description:
          type: string
        price:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
        stock_quantity:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        slug:
          type: string
          maxLength: 50
          pattern: ^[-a-zA-Z0-9_]+$
      required:
      - description
      - id
      - name
      - slug
    MedicationPOST:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 100
        medication_image:
          type: string
          format: uri
        description:
          type: string
        price:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
        stock_quantity:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
      required:
      - description
      - id
      - name
    Order:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        medication_price:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
          readOnly: true
        quantity:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        order_date:
          type: string
          format: date-time
          readOnly: true
        total_price:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
          readOnly: true
        transaction_id:
          type: string
          readOnly: true
        customer:
          type: integer
        medication:
          type: integer
          nullable: true
      required:
      - id
      - medication_price
      - order_date
      - total_price
      - transaction_id
    PatchedCustomer:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        address:
          type: string
        phone_number:
          type: string
          maxLength: 15
        user:
          type: integer
    PatchedMedicationPOST:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 100
        medication_image:
          type: string
          format: uri
        description:
          type: string
        price:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
        stock_quantity:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
    PatchedOrder:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        medication_price:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
          readOnly: true
        quantity:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        order_date:
          type: string
          format: date-time
          readOnly: true
        total_price:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
          readOnly: true
        transaction_id:
          type: string
          readOnly: true
        customer:
          type: integer
        medication:
          type: integer
          nullable: true
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
