# Generated by Django 5.0.3 on 2024-03-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_fakeorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='image',
            field=models.CharField(default='product_07.png', max_length=100),
        ),
    ]
