# Generated by Django 5.0.3 on 2024-03-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_medication_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='image',
            field=models.CharField(default='product_07.png', max_length=100, null=True),
        ),
    ]
