# Generated by Django 5.0.3 on 2024-03-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_alter_medication_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='image',
            field=models.CharField(max_length=100),
        ),
    ]
