# Generated by Django 5.0.3 on 2024-03-31 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0007_medication_short_description_medication_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakeorder',
            name='medication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.medication'),
        ),
    ]
