# Generated by Django 5.0.3 on 2024-03-31 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0008_alter_fakeorder_medication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakeorder',
            name='medication_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
