# Generated by Django 5.0.3 on 2024-04-01 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0009_alter_fakeorder_medication_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='medication_image',
            field=models.ImageField(default='', upload_to='pharmacy/images'),
        ),
    ]
