# Generated by Django 5.0.3 on 2024-04-01 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0010_medication_medication_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='medication_image',
            field=models.ImageField(default='default_image.png', upload_to='pharmacy/images'),
        ),
    ]
