# Generated by Django 5.0.3 on 2024-04-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0011_alter_medication_medication_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='medication_image',
            field=models.ImageField(default='pharmacy/images/default_image.png', upload_to='pharmacy/images'),
        ),
    ]
