# Generated by Django 5.0.3 on 2024-04-01 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0012_alter_medication_medication_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='image',
        ),
    ]
