# Generated by Django 5.0.3 on 2024-04-02 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0013_remove_medication_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='fakeorder',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.customer'),
        ),
    ]
