# Generated by Django 5.0.3 on 2024-04-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0014_fakeorder_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='medication',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
