# Generated by Django 5.0.3 on 2024-04-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0015_alter_medication_price_alter_medication_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='fakeorder',
            name='transaction_id',
            field=models.CharField(default=None, editable=False, max_length=20, unique=True),
        ),
    ]
