# Generated by Django 5.0.3 on 2024-04-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0016_fakeorder_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakeorder',
            name='transaction_id',
            field=models.CharField(default='', editable=False, max_length=20, unique=True),
        ),
    ]
