# Generated by Django 5.0.3 on 2024-04-02 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0017_alter_fakeorder_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='medication_price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(default='', editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='medication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.medication'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=None, editable=False, max_digits=10),
        ),
        migrations.DeleteModel(
            name='FakeOrder',
        ),
    ]
