# Generated by Django 5.0.3 on 2024-04-03 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0018_order_medication_price_order_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='sale',
            field=models.BooleanField(default=False),
        ),
    ]
